### ISSUE TITLE
i Can't do it on DFP

### ISSUE THREAD

**Issue by Ashwinpk** [epicserve/expandable-ads#1]
i tried to do this on my DFP but i am getting more errors you can please describe the process step by step how to make this ads with DFP

**Comment by epicserve** [comment]
I haven't touched this code in over 6 years. Sorry, I'm not going to be able to help you. Maybe there is another project out there that does what you're wanting.

**Comment by Ashwinpk** [comment]
please sent me that project link

**Comment by Ashwinpk** [comment]
Still this DFP trick is being used on many sites that why i am searching for this trick

**Comment by epicserve** [comment]
@Ashwinpk,

I haven't used DFP in over 6 years. I can not help you. I don't know of another project. You'll have to try and find one.
