### ISSUE TITLE
when i put my placement its not working please help

### ISSUE THREAD

**Issue by Ashwinpk** [epicserve/expandable-ads#2]
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Expandable Ads</title>

        
        <script type='text/javascript' src='http://partner.googleadservices.com/gampad/google_service.js'>
        </script>
        <script type='text/javascript'>
        GS_googleAddAdSenseService("ca-pub-################");
        GS_googleEnableAllServices();
        </script>
        <script type='text/javascript'>
        GA_googleAddSlot("ca-pub-################", "My_Ad_Unit_or_Placement");
        </script>
        <script type='text/javascript'>
        GA_googleFetchAds();
        </script>
        

    </head>

    <body>

        <div id="my-ad-container" style="position: relative; width: 960px; height: 66px;">
        
        <script type='text/javascript'>
        GA_googleFillSlot("My_Ad_Unit_or_Placement");
        </script>
        </div>

    </body>
</html>

**Comment by epicserve** [comment]
@Ashwinpk,

See my comments in https://github.com/epicserve/expandable-ads/issues/1.
